all: server client main

client: client.o connector.o

server: server.o connector.o

.PHONY: al

#server: server.o
#	gcc -o server server.o
#main: main.o
#	gcc -o main main.o
#
#main.o:	main.c
#	gcc -c main.c
#server.o:	server.c
#	gcc -c server.c
#
#clean:
#	rm main.o main server server.o
